### PR TITLE
Fixed link to apple touch icon

### PR DESCRIPTION
**Pull request by AndrewCarterUK**
Should not be relative path

### CODE REVIEW

**Comment by reinink** [comment]
Are you certain? You could very well be right, but does this still work when you're on a subpage, and choose to bookmark the site?

**Comment by AndrewCarterUK** [comment]
The url of the icon is: http://www.php-fig.org/apple-touch-icon.png

So if you were on a subpage, you would need to reference this from the path relative to the root of the site.

Happy for you to wait for a second opinion, I created the PR because when I was on a sub page and clicked the link in the source I got a 404 :)

**Comment by reinink** [comment]
Oh my goodness, I misread this. I thought you were removing the slash, not adding it. My bad. Yes, this is totally correct.

@philsturgeon Please merge in good sir.

**Comment by reinink** [comment]
Thanks @simensen ;)

**Comment by AndrewCarterUK** [comment]
Not a problem, good work on the site - looks awesome

**Pull request merged**
