### PR TITLE
Website redesign

### PR DESCRIPTION
**Pull request by reinink**
Okay wow, I'm actually creating the PR for this after picking away at it for almost 2 years! The new website is at the point that I believe it can go live. It may not be perfect in every way, but I can promise it's a huge step up from the current site, and we can always continue to tweak some of the minor details.

You can preview the site [here](http://php-fig.reinink.ca/).

image

Pinging @simensen and @philsturgeon to have a quick review.

### CODE REVIEW

**Comment by simensen** [comment]
Great work, @reinink! I took a quick look and all seems in order. I'm sure the fun can begin now on the list w/ people chiming in on choices for text and what-not.

---

To start the bikeshedding, I had one thing that jumped out at me: "Standards Recommendations" being the primary navigation link for the PSR index. I don't know that many people know them as "Standards Recommendations" but *many* people know about (or have heard about) PSR. In fact, many people are likely to go to PHP-FIG after searching for "PSR". I don't know a good solution to this short of changing the link to "PSR's" or "PSR Index" ; I'm not sure how we properly pluralize PSR (PSRs? PSR's?) so maybe "PSR Index" would be a good choice as it is still shorter, has PSR, and actually says what that page is.. and index of the PSR's. We also have a link that says, "View Recommendations" so I guess another option would be to have the primary navigation simply be, "Recommendations" but I think having PSR in the name might be better.

**Comment by reinink** [comment]
@simensen Hah, I actually only had "Recommendations" in my initial design, but you felt it was important to add "Standards" to it. I don't love it either, but I'm also not a big fan of "PSRs" on its own. Yes, some folks will come to the site knowing what that means, but what about the huge audience that doesn't? I've tried very hard to make the new site approachable for those who know next to nothing about the PHP-FIG, or the PSRs.

We could do "PSR Recommendations":

image

Or "Recommendations (PSRs)":

image

But IMHO simply putting "PSR" is going to be very unhelpful for those "not in the know":

image

My vote would be "Recommendations":

image

We can always add "PSR" to the home page button to make this clearer:

image

And I've already added "PSR" to each item in the home page feature list:

image

**Comment by michaelcullum** [comment]
Wow, this is a huge improvement. :+1: to `Recommendations (PSRs)` in the header although I'd also suggest changing the `View Recommendations` home page button to `View PSRs` (Which would be the pluralisation of PSR).

Also, we need to be careful with regards to the home pages when we get standards that don't fit into the three existing categories. PHP Doc is coding style kind of but PSR-9, PSR-10 and PSR-Version don't really fit into any of those categories.

The other thing that concerns me slightly is that people may miss the PSRs on the homepage (the approved PSRs) and instead jump straight to /psr/ which includes a lot of the WIP PSRs. I'm not entirely sure how we could solve that problem whilst keeping it clean and aesthetically pleasing: Second menu of Approved PSRs (probably ugly and not very scalable), a dropdown on the Recommendations menu item listing approved PSRs (dropdowns are kinda nightmarish UX with touch). Thoughts?

**Comment by simensen** [comment]
@reinink Sounds about right. :) I'm always going back-and-forth on this kind of thing and to be honest I was fairly certain I'd remembered discussing it before and probably being the one pushing for "Standards Recommendations." Now with the final design it seemed off (especially w/ the mobile nav) because it is so much longer than the other navigation items. Probably not a huge deal.

At the end of the day, I should have not said anything. I don't intend to get into the design stuff too much as I know it is something that I could quite easily get sucked into and I don't have time for that right now. :) Again, great work! I'm sure it will come together nicely. Thanks again. :)

**Comment by reinink** [comment]
> Again, great work!

Thanks man, I'm really happy with it and too feel it's a huge improvement. However...

> I'm sure it will come together nicely.

For me I'm sort of at the end of the road with this project. It's been ongoing for a LONG time, and I have a ton of hours into it. I'm not sure I'm prepared to going in circles doing design revisions and content tweaks. I simply do not have the capacity. I need to hand this off and move on at this point.

I'd really love to just agree that this is a MASSIVE improvement over [this](http://www.php-fig.org/), pull it in, and then begin the bike-shedding on a per issue basis. At this point I'll give this PR a day or two, and if the requests/changes are minor, I'll implement them, but beyond that I'm going to have to say no. If for some reason the group doesn't feel it can be pulled in within this timeframe, then I'd love if someone could fork my repo, or create a branch on the main repo for it, and then continue the work on it from there.

I hope this is understandable.

**Comment by simensen** [comment]
> I hope this is understandable.

Totally. :)

It is a little out of my hands at this point. I think the best thing will be to turn it over to the website team (currently @pmjones & @dragoonis) and see if they want to click the green button and then start making tweaks from there.

**Comment by reinink** [comment]
@simensen :+1: 

@michaelcullum:

> Also, we need to be careful with regards to the home pages when we get standards that don't fit into the three existing categories. PHP Doc is coding style kind of but PSR-9, PSR-10 and PSR-Version don't really fit into any of those categories.

We can always recategorize in the future. This list makes sense right now (as it helps give some context to work that the FIG does), but you're absolutely right, it may be incomplete in 6 months. I'd recommend changing it at that point. It's not really a problem that has to be solved today.

> The other thing that concerns me slightly is that people may miss the PSRs on the homepage (the approved PSRs) and instead jump straight to /psr/ which includes a lot of the WIP PSRs. I'm not entirely sure how we could solve that problem whilst keeping it clean and aesthetically pleasing: Second menu of Approved PSRs (probably ugly and not very scalable), a dropdown on the Recommendations menu item listing approved PSRs (dropdowns are kinda nightmarish UX with touch). Thoughts?

I don't really see this as an issue, given that the first category of PSRs on the recommendations page is the accepted PSRs.

**Comment by montogeek** [comment]
@reinink Great work!!! :)

**Comment by dragoonis** [comment]
Thanks @reinink for the work, I've been patiently waiting for this, as I'm sure other folks have too!

The website we have right now that @bobthecow and myself initially put together has out-lived itself and it's time to embrace the new sexyness.

The content of the website is out of date, as per the coordinators,editors ..etc on some PSR's. Is this just the case of the gitsubmodule commit ref that you've got registered. If you updated that ref would the editors update? Please advise. 

I'd like to consider merging this, but don't want to push live incorrect information.

Thanks.

**Comment by michaelcullum** [comment]
@dragoonis No more out of date than it already is though http://www.php-fig.org/psr/

**Comment by dragoonis** [comment]
@michaelcullum fair point. Is it possible to update the ref then and prove that it's working on the design before I merge this? /cc @reinink

**Comment by michaelcullum** [comment]
@dragoonis You also haven't updated the index.md which would explain it https://github.com/php-fig/fig-standards/blob/master/index.md

**Comment by dragoonis** [comment]
@michaelcullum got it. will update that main file shortly.

**Comment by reinink** [comment]
Yep, the "includes" git submodule should already be updated to the most recent version.

**Comment by reinink** [comment]
Also, if you're going to updated the [index.md](https://github.com/php-fig/fig-standards/blob/master/index.md) file, it would be awesome if you could merge the first two sentences together about statuses together. Having them in separate paragraphs doesn't really make sense.

**Comment by dragoonis** [comment]
I've already updated index.md, just for PSR-6. If you want more changes to index.md can you make a PR against it ?

**Comment by michaelcullum** [comment]
php-fig/fig-standards#653

**Comment by philsturgeon** [comment]
:+1: to `Recommendations (PSRs)`.

I'd be a big fan of the "Merge this then bikeshed later" approach obviously. This has taken you an incredible amount of time and effort to work on, and people should be ready to take that on themselves once its part of the project, instead of throwing 50 opinions at you and making you cater to them all.

Let's merge this and hand it off to our web master @simensen? :)

**Comment by philsturgeon** [comment]
"our" says the guy who quit.

**Comment by michaelcullum** [comment]
@philsturgeon You're behind. @simensen has left too now. :(

**Comment by dragoonis** [comment]
@michaelcullum your change is good. @reinink are you happy with #653 wording ?

**Comment by philsturgeon** [comment]
Figured he was still webmaster like I’m still randomly domain holder and occasional PR merger.

Whoever is responsible for the website should take this off on reinink so he can get back to working on the PHP League for free. :p

**Comment by dragoonis** [comment]
@philsturgeon I've deferred taking the domain off your hands, until I need to, will pick that up in the near future.

I'm going to merge this now.

**Comment by reinink** [comment]
NICE!!! :+1:

**Comment by philsturgeon** [comment]
xebpiwk

**Comment by reinink** [comment]
> Whoever is responsible for the website should take this off on reinink so he can get back to working on the PHP League for free. :p

LOL

**Comment by dragoonis** [comment]
@reinink I made some tweaks to the main FIG repo, including michael's description update. Can you make a PR to update the submodule commit ref so the website is syned up?

**Comment by reinink** [comment]
@dragoonis Yep!

**Comment by sergeyklay** [comment]
On pages where a lot of code it is more logical to allocate for it more space

selection_001

**Comment by michaelcullum** [comment]
@sergeyklay Make a new issue on the repo. ;)

**Comment by reinink** [comment]
@michaelcullum @sergeyklay Yup, create an new issue for this if you don't mind. The site's going to have a few little glitches, so thanks for reporting this one!

**Pull request merged**
