### PR TITLE
Updated Slim project rep from Josh Lockhart to Jason Coward

### PR DESCRIPTION
**Pull request by squinones**
Updated Slim project rep from Josh Lockhart to Jason Coward

### CODE REVIEW

**Comment by reinink** [comment]
Good morning Samantha! Are you sure that's the correct Twitter handle? The name on that account is "Marc Mauri Alloza".

**Comment by reinink** [comment]
Looks like it should maybe be https://twitter.com/drumshaman?

**Comment by squinones** [comment]
That's what I get for trusting @codeguy :p 

Updated

**Comment by reinink** [comment]
NEVER TRUST JOSH! 🙊

**Comment by codeguy** [comment]
haha. My bad! I was looking at his Slack handle by mistake.

**Pull request merged**
