### PR TITLE
sabre/dav got stylized differently.

### PR DESCRIPTION
**Pull request by evert**
Since a year or two we started stylizing SabreDAV as sabre/dav. I hope this change can also be reflected on the PHP-FIG website.

### CODE REVIEW

**Comment by evert** [comment]
Light speed. Thank you!

**Comment by simensen** [comment]
Indeed. I thought I was going to be super on top of this one tonight and BAM. Seconds later... :)

**Comment by pmjones** [comment]
Insomnia. :-/

**Comment by dragoonis** [comment]
:+1:

**Comment by evert** [comment]
Sorry to hear that @pmjones =(

**Pull request merged**
