### PR TITLE
Remove recent resignations

### PR DESCRIPTION
**Pull request by salathe**
- Doctrine: https://groups.google.com/forum/#!topic/php-fig/3PGhfQGoCj8
- Guzzle: https://groups.google.com/forum/#!topic/php-fig/mnqZ5ztS-pM
- Laravel: https://groups.google.com/forum/#!topic/php-fig/HWX2IeiRx9Y
- Propel: https://groups.google.com/forum/#!topic/php-fig/HgjJJXhDYsc
- sabre/dav: https://groups.google.com/forum/#!topic/php-fig/FV4aL-noVZk

### CODE REVIEW

**Comment by salathe** [comment]
:cry:

**Comment by salathe** [comment]
Thanks @dragoonis :bow:

**Comment by dragoonis** [comment]
Nae danger :)

**Comment by evert** [comment]
My soul has been released!

**Pull request merged**
