### PR TITLE
Updated ZF advisor

### PR DESCRIPTION
**Pull request by weierophinney**
I (@weierophinney) will be taking over for @padraicb.

### CODE REVIEW

**Comment by Saeven** [comment]
Matthew for president!

**Comment by dragoonis** [comment]
@weierophinney what about paddy as a sponsor for PSR-6 ? Does he remain? Do we update sponsors respectively ?

**Comment by weierophinney** [comment]
@dragoonis Yes, feel free; I may solicit a new sponsor, as I want to be involved with some other current proposals, but I'm up-to-date on PSR-6 and can assist with the end stages. I'll ping @Crell to verify he's okay with that.

**Comment by dragoonis** [comment]
@weierophinney it'd be good to have an active member's name against an active proposal. If it's for old proposals and those members have now left, that's totally fine with me.

**Pull request merged**
